language: objective-c

script:
  - script/rspec-ci
  - script/unit-ci
  - script/cucumber-ci.rb --tags ~@no_ci
  - script/install-gem-ci.rb

rvm:
  - 1.9.3
  - 2.1.0
  - 2.1.1

notifications:
  email: false
